name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        gulp build:portal --gulpfile gulpfile-dist.js
      env:
        CI: true
    - name: Add & Commit
      uses: EndBug/add-and-commit@v2.3.2
      with:
        # The name of the user that will be displayed as the author of the commit
        author_name: # optional
        # The email of the user that will be displayed as the author of the commit
        author_email: # optional
        # The directory where your repository is located. You should use actions/checkout first to set it up
        cwd: # optional, default is .
        # Whether to use the force option on git add, in order to bypass eventual gitignores
        force: # optional, default is false
        # The message for the commit
        message: # optional, default is Commit from GitHub Actions
        # The path to stage files from
        path: # optional, default is .
        # The pattern that mathces file names
        pattern: # optional, default is *.*
